modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="dynamictrees"
type = "required"
versionRange="[1.5.0-BETA01,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cobblemon"
type = "required"
versionRange="[1.6.1,1.7.0)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="cobblemontrees.mixins.json"